name: CD SpringBoot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permisos para Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Ejecutar pruebas automatizadas
        run: ./gradlew test

      - name: Construir el proyecto (Generar JAR)
        run: ./gradlew build

      - name: Publicar el artefacto JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar-release
          path: build/libs/*.jar